fa: 576.9762479490852
gm:
  dynamics: pullback
  h_value: 0.0
  kx: 2
  ky: 1
  lambda_value: 1.0
  likelihood: identity
  noise:
    gm_color_noise_kernel_sigma: 2.0
    gm_color_noise_kernel_size: 51
    gm_noise_type: color
    gm_white_noise_mu: 0.0
    gm_white_noise_sigma: 1.0
gp:
  T: 100
  dt: 0.1
  name: lotka
mse: 0.5331867430207428
optimizer:
  lr: 0.01
  num_steps: 100
